---
title: "Post DBEM data analysis for manuscript"
author: "William W.L. Cheung, Juliano Palacios Abrantes, Sarah Roberts"
date: "18/05/2022"
output: html_document
---

---
title: "pre_dbem"
author: "Sarah Roberts"
date: "5/4/2022"
output: html_document
---

```{r}
# For grid estimation and species selection
library(tidyverse)
library(sf)
library(viridis)
library(wesanderson)
library(worms)

# Fix new updates of sf package
sf::sf_use_s2(use_s2 = FALSE)

# For collaborative ease
library(here)

```



# Results

# Figure 1


```{r}
# MPA test grid
grids <- read_csv(here("./Data/mpa_scenarios/grid_m5point5.csv")) %>% 
  select(lon = coords.x1,
         lat = coords.x2,
         prop,
         status) %>% 
  mutate(cons_scen = 5) %>% 
  bind_rows(read_csv(here("./Data/mpa_scenarios/grid_30.csv")) %>% 
              select(lon = coords.x1,
                     lat = coords.x2,
                     prop,
                     status) %>% 
              mutate(cons_scen = 30)
  ) %>% 
  bind_rows(read_csv(here("./Data/mpa_scenarios/grid_15.csv")) %>% 
              select(lon = coords.x1,
                     lat = coords.x2,
                     prop,
                     status) %>% 
              mutate(cons_scen = 15)
  ) %>% 
  mutate(status = replace_na(status,"no protection"))



# test <- grids %>%
  # filter(status == "surrounding") %>%
  # mutate(bins = cut(prop, breaks = 3))

# Load worlkd map
World_map <- rnaturalearth::ne_countries(scale = 'large', returnclass = c("sf"))
meow_sf <- st_read("../Data/spatial/MEOW/meow_ecos.shp") %>% 
  filter(REALM %in% c("Temperate Northern Atlantic","Arctic"))




  ggplot() +
    # geom_sf(data = World_map, aes()) +
    # geom_tile(data = subset(grids, !is.na(bins)),
    geom_tile(data = grids,
    aes(
      x = lon,
      y = lat,
      fill = status,
      color = status
    ),
    alpha = 0.7
  ) +
    geom_sf(dat = meow_sf, aes(), color = "black", fill =NA) +
    geom_sf(data = World_map, aes(), fill = "grey90") +
    scale_fill_manual("Conservation status",values = c(
      "white",
      wes_palette("Zissou1")[5],
      "darkblue"
      # wes_palette("Rushmore1")[3]
    )
                      ) +
    scale_color_manual("Conservation status",values = c(
      "white",
      wes_palette("Zissou1")[5],
      "darkblue"
      # wes_palette("Rushmore1")[3]
      
                                 )
                      ) +
    # scale_fill_viridis("Conservation status", discrete = T, alpha = 0.7,option = "D",direction = -1) +
    # scale_color_viridis("Conservation status",discrete = T, alpha = 0.7,option = "D",direction = -1) +
    theme_bw() +
    labs(x = "Longitude", y = "Latitude") +
    theme(legend.position = "") +
    facet_wrap(~cons_scen) +
    coord_sf(xlim = c(-42.5,69),
             ylim = c(35,90)
             ) +
    ggsave("../Figures/scenarios_a_ch.png",
           width = 10,
           height = 5
           )
```



Double check the DBEM is doing what we want it to do

```{r read_data}

# MPA test grid
grid_30 <- read_csv(here("./Data/mpa_scenarios/grid_30.csv"))

mpa_grid <- grid_30 %>% 
  select(index = gridID,status,prop)

unique(mpa_grid$status)

# DBEM lat lon
coords <- read.csv(here("./Data/Lon_Lat_DBEM.txt"),header = F) %>% 
  select(index = V1,
         lon = V2,
         lat = V3)


# MCP data
mcp_data <- read.table("/Volumes/Enterprise/Data/northsea_mpa_sust_fish/Raw/C6IPSLtest/600069/600069Catch2020.txt", quote="\"", comment.char="")
colnames(mcp_data) <- c("index","mcp")

# ABD data
abd_data <- read.table("/Volumes/Enterprise/Data/northsea_mpa_sust_fish/Raw/C6IPSLtest/600069/600069Abd2020.txt", quote="\"", comment.char="")
colnames(abd_data) <- c("index","abd")

# Join both

test_data <-
  mcp_data %>% 
  full_join(abd_data) %>% 
  gather("var","value",mcp:abd)





```

```{r}

test_data %>% 
  left_join(coords) %>% 
  ggplot() +
  geom_tile(
    aes(
      x = lon,
      y = lat,
      fill = value
    )
  ) +
  facet_wrap(~var)

```



```{r}

# Compare catch between surrounding and open ocean
# Surrounding should be more, at least in average
test_data %>% 
  left_join(mpa_grid) %>% 
  mutate(value = ifelse(is.na(value),0,value),
         status = ifelse(is.na(status),"open",status)
         ) %>% 
  group_by(status,var) %>% 
  summarise(
    sum = sum(value, na.rm = T),
    mean = mean(value, na.rm = T),
    n = n()
  )




```



```{r check_protected_areas}

test_data %>% 
  left_join(mpa_grid) %>% 
  mutate(value = ifelse(is.na(value),0,value),
         status = ifelse(is.na(status),"open",status)
         ) %>% 
  filter(status == "protected")




```

```{r map_me}

map_data <- mpa_grid %>% 
  left_join(coords,
            by = "index") %>% 
  left_join(test_data,
            by = "index") %>%
  mutate(status = ifelse(is.na(status),"open",status)) %>% 
  filter(!is.na(value))


World_map <- rnaturalearth::ne_countries(scale = 'large', returnclass = c("sf"))

ggplot() +
  geom_sf(data = World_map, aes()) +
  geom_sf(data = fao_regions, aes()) +
  geom_tile(data = map_data,
    aes(
      x = lon,
      y = lat,
      fill = value,
      color = value
    )
  )


```



# Table S1

*Can you please get the number of fishes and invertebrates, and create a table that list the species as a supplementary table? Here is the final list of species:* https://drive.google.com/open?id=1xlsMJGGVTIax9GQXoMVOx8EgFC1eNgbU&authuser=wwlcheung%40gmail.com&usp=drive_fs


```{r}


nea_spplist <- read_csv("../Data/species/nea_spplist.csv")
final_spplist <- read_csv("../Data/species/final_spplist.csv")

# Get info necessary
ssplit <- nea_spplist %>% 
  filter(taxon_key %in% final_spplist$x)

# Cerate Table S1 using worms
table_s1 <- worms::wormsbynames(ssplit$taxon_name) %>% 
  mutate(vert_invert = ifelse(phylum == "Chordata","vertebrate","invertebrate")) %>% 
  select(taxon_name=valid_name,kingdom:genus,vert_invert) %>% 
  left_join(ssplit,
            by = "taxon_name") %>% 
  select(taxon_name,common_name,kingdom:genus.x,vert_invert)

# Write table for paper
write_csv(table_s1,"../Data/table_s1.csv")

# Estimate numbers for intext
table_s1 %>% 
  group_by(vert_invert) %>% 
  tally()
   



```


# Bugs

## Test F075 bug

```{r}

library("tidyverse")
library("here")

Lon_Lat_DBEM <- read.csv("Data/Lon_Lat_DBEM.txt", header=F)
colnames(Lon_Lat_DBEM) <- c("index","lon","lat")

grid_mpa <- read_csv(here("./Data/mpa_scenarios/grid_30.txt")) %>% 
  select(index = gridID, zone = zone.x,status,prop)


grid_mpa <- read_csv(here("./Data/mpa_scenarios/grid_15.csv")) %>% 
  select(index = gridID, zone = zone.x,status,prop)



load("~/Desktop/600054Catch.RData")


abd <- as.data.frame(sppabdfnl) 
colnames(abd) <- seq(1951,2100,1)

abd <- abd %>% 
  bind_cols(coords) %>% 
  gather("year",'value',1:150) %>% 
  filter(!is.na(value))


# Linear value
grid_mpa %>% 
  left_join(abd,
            by = "index") %>% 
  # filter(status != "open") %>%
  # View()
  # mutate(status = ifelse(is.na(status),"open",status)) %>% 
  # View()
  group_by(year,status) %>% 
  summarise(m = mean(value,na.rm=T)) %>%
  # View()
  ggplot() +
  geom_line(
    aes(
      x = as.numeric(year),
      y = log10(m),
      color = status
    )
  )

```

