---
title: "pre_dbem"
author: "Sarah Roberts"
date: "5/4/2022"
output: html_document
---

```{r}
library(sf)
library(spatialEco)
```


#grid 
for dbem grid that is overlapping FAO27 
randomly select 30 points 
from those 30 points figure out which points are surrounding them (within .75 dec.degrees to get the diagonal)

```{r}
fao_27 <- read_sf("../Data/Zone_27.shp")


grid <- read.csv("../Data/Lon_Lat_DBEM.txt", header = FALSE)
colnames(grid) <- c("gridID", "long", "lat")
grid_sp <- st_as_sf(grid, coords = c("long", "lat"), crs = st_crs(fao_27))


sf::sf_use_s2(FALSE)
grid_intersect_27 <- point.in.poly(grid_sp, fao_27)
grid_intersect_27 <- 
grid_intersect_27_df <- as.data.frame(grid_intersect_27) 

grid_intersect_27_df <- grid_intersect_27_df[!is.na(grid_intersect_27_df$zone), ]

ggplot() + geom_sf(data = world) + 
  geom_sf(data = fao_27) + #adding in group = Name makes ggplot know how to group the spatial object
  geom_point(data = grid_intersect_27_df, aes(x = coords.x1, y = coords.x2, size = .2)) + 
  coord_sf(xlim=c(-80, -65), ylim=c(34,46), expand = TRUE)+ 
  theme(panel.background = element_rect(fill = "white", colour = "black"),
        legend.position="bottom",
        legend.title=element_blank(),
        plot.title = element_text(hjust = 0.5)) + 
  labs(y = element_blank(), x = element_blank()) + 
  ggtitle("Ecomon Data", subtitle ="1997")+ guides(color = guide_legend(override.aes = list(size = 0.5))) + guides(col = guide_legend(nrow = 2))

```
